spring.application.name=orderService

# Server
server.servlet.context-path=/api/v1/orders
server.port=9020

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-location=classpath:data.sql

#Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
